version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=hernaneta777
    volumes:
      - ./dbdata:/opt/couchdb/data
  client1:
    container_name: app-prod
    image: app-prod
    build:
      context: .
      target: production