version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=hernaneta777
      - COUCHDB_REMOTE_URL=http://e-mat.fi.mdp.edu.ar:5984
    volumes:
      - ./dbdata:/opt/couchdb/data